CREATE DATABASE IF NOT EXISTS cargo_pickup DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE cargo_pickup;

DROP TABLE IF EXISTS waybill;
CREATE TABLE waybill (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    waybill_no VARCHAR(64) NOT NULL COMMENT '运单号',
    flight_no VARCHAR(32) COMMENT '航班号',
    arrival_time DATETIME COMMENT '到达时间',
    cargo_name VARCHAR(128) COMMENT '货物名称',
    cargo_weight DECIMAL(12,2) COMMENT '货物重量',
    cargo_pieces INT COMMENT '货物件数',
    cargo_unit VARCHAR(16) COMMENT '计量单位',
    cargo_owner VARCHAR(128) COMMENT '货主',
    cargo_owner_contact VARCHAR(32) COMMENT '货主联系方式',
    cargo_status VARCHAR(32) DEFAULT 'NORMAL' COMMENT '货物状态',
    lock_reason VARCHAR(256) COMMENT '锁定原因',
    lock_time DATETIME COMMENT '锁定时间',
    lock_operator VARCHAR(64) COMMENT '锁定操作人',
    unpaid_amount DECIMAL(12,2) DEFAULT 0 COMMENT '欠费金额',
    storage_location VARCHAR(64) COMMENT '库位',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX idx_waybill_no (waybill_no),
    INDEX idx_cargo_owner (cargo_owner),
    INDEX idx_status (cargo_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运单表';

DROP TABLE IF EXISTS vehicle;
CREATE TABLE vehicle (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    plate_number VARCHAR(16) NOT NULL COMMENT '车牌号',
    vehicle_type VARCHAR(32) COMMENT '车辆类型',
    vehicle_color VARCHAR(16) COMMENT '车辆颜色',
    vehicle_license_no VARCHAR(32) COMMENT '行驶证号',
    license_expire_date DATE COMMENT '行驶证有效期',
    vehicle_license_img VARCHAR(256) COMMENT '行驶证照片',
    insurance_no VARCHAR(64) COMMENT '保险单号',
    insurance_expire_date DATE COMMENT '保险有效期',
    driver_id VARCHAR(32) COMMENT '司机ID',
    driver_name VARCHAR(64) COMMENT '司机姓名',
    driver_phone VARCHAR(16) COMMENT '司机电话',
    driver_license_no VARCHAR(32) COMMENT '驾驶证号',
    driver_license_expire_date DATE COMMENT '驾驶证有效期',
    driver_license_img VARCHAR(256) COMMENT '驾驶证照片',
    id_card_no VARCHAR(32) COMMENT '身份证号',
    id_card_expire_date DATE COMMENT '身份证有效期',
    id_card_img VARCHAR(256) COMMENT '身份证照片',
    forwarder_id VARCHAR(32) COMMENT '货代ID',
    forwarder_name VARCHAR(128) COMMENT '货代名称',
    status TINYINT DEFAULT 1 COMMENT '状态',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX idx_plate_number (plate_number),
    INDEX idx_driver_id (driver_id),
    INDEX idx_forwarder_id (forwarder_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='车辆表';

DROP TABLE IF EXISTS booking;
CREATE TABLE booking (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    booking_no VARCHAR(64) NOT NULL COMMENT '预约单号',
    forwarder_id VARCHAR(32) COMMENT '货代ID',
    forwarder_name VARCHAR(128) COMMENT '货代名称',
    forwarder_contact VARCHAR(32) COMMENT '货代联系方式',
    waybill_id VARCHAR(32) COMMENT '运单ID',
    waybill_no VARCHAR(64) COMMENT '运单号',
    vehicle_id VARCHAR(32) COMMENT '车辆ID',
    plate_number VARCHAR(16) COMMENT '车牌号',
    driver_id VARCHAR(32) COMMENT '司机ID',
    driver_name VARCHAR(64) COMMENT '司机姓名',
    driver_phone VARCHAR(16) COMMENT '司机电话',
    expected_arrival_start DATETIME COMMENT '预计到场开始时间',
    expected_arrival_end DATETIME COMMENT '预计到场结束时间',
    actual_arrival_time DATETIME COMMENT '实际到场时间',
    queue_position INT COMMENT '排队位置',
    queue_id VARCHAR(64) COMMENT '排队ID',
    status VARCHAR(32) NOT NULL COMMENT '预约状态',
    pickup_order_no VARCHAR(64) COMMENT '提货单号',
    ownership_verified TINYINT DEFAULT 0 COMMENT '货权是否确认',
    ownership_operator VARCHAR(64) COMMENT '货权确认人',
    ownership_time DATETIME COMMENT '货权确认时间',
    ownership_remark VARCHAR(512) COMMENT '货权确认备注',
    security_checked TINYINT DEFAULT 0 COMMENT '安保是否检查',
    security_operator VARCHAR(64) COMMENT '安保检查人',
    security_time DATETIME COMMENT '安保检查时间',
    security_remark VARCHAR(512) COMMENT '安保检查备注',
    start_time DATETIME COMMENT '开始提货时间',
    start_operator VARCHAR(64) COMMENT '开始提货操作人',
    complete_time DATETIME COMMENT '完成提货时间',
    complete_operator VARCHAR(64) COMMENT '完成提货操作人',
    total_pieces INT COMMENT '总件数',
    picked_pieces INT DEFAULT 0 COMMENT '已提件数',
    partial_delivery TINYINT DEFAULT 0 COMMENT '是否部分放货',
    partial_reason VARCHAR(512) COMMENT '部分放货原因',
    reject_reason VARCHAR(512) COMMENT '驳回原因',
    cancel_reason VARCHAR(512) COMMENT '取消原因',
    platform_no VARCHAR(16) COMMENT '月台号',
    remark VARCHAR(512) COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX idx_booking_no (booking_no),
    INDEX idx_waybill_no (waybill_no),
    INDEX idx_plate_number (plate_number),
    INDEX idx_status (status),
    INDEX idx_queue_position (queue_position),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约单表';

DROP TABLE IF EXISTS queue_item;
CREATE TABLE queue_item (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    queue_code VARCHAR(64) NOT NULL COMMENT '排队编号',
    booking_id BIGINT NOT NULL COMMENT '预约ID',
    booking_no VARCHAR(64) COMMENT '预约单号',
    plate_number VARCHAR(16) COMMENT '车牌号',
    driver_name VARCHAR(64) COMMENT '司机姓名',
    position INT NOT NULL COMMENT '排队位置',
    priority INT DEFAULT 10 COMMENT '优先级',
    join_time DATETIME COMMENT '加入时间',
    leave_time DATETIME COMMENT '离开时间',
    leave_reason VARCHAR(256) COMMENT '离开原因',
    requeue_count INT DEFAULT 0 COMMENT '重新排队次数',
    estimated_call_time DATETIME COMMENT '预计叫号时间',
    status VARCHAR(16) DEFAULT 'ACTIVE' COMMENT '状态',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX idx_queue_code (queue_code),
    INDEX idx_booking_id (booking_id),
    INDEX idx_position (position),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排队队列表';

DROP TABLE IF EXISTS operation_log;
CREATE TABLE operation_log (
    id BIGINT PRIMARY KEY COMMENT '主键ID',
    booking_id BIGINT COMMENT '预约ID',
    booking_no VARCHAR(64) COMMENT '预约单号',
    operation_type VARCHAR(32) COMMENT '操作类型',
    from_status VARCHAR(32) COMMENT '原状态',
    to_status VARCHAR(32) COMMENT '目标状态',
    operator_id VARCHAR(64) COMMENT '操作人ID',
    operator_name VARCHAR(64) COMMENT '操作人姓名',
    operator_role VARCHAR(32) COMMENT '操作人角色',
    operate_time DATETIME COMMENT '操作时间',
    operate_ip VARCHAR(64) COMMENT '操作IP',
    remark VARCHAR(512) COMMENT '备注',
    reason VARCHAR(512) COMMENT '原因',
    before_data TEXT COMMENT '操作前数据',
    after_data TEXT COMMENT '操作后数据',
    extra_info TEXT COMMENT '扩展信息',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    create_by VARCHAR(64) COMMENT '创建人',
    update_by VARCHAR(64) COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX idx_booking_id (booking_id),
    INDEX idx_booking_no (booking_no),
    INDEX idx_operate_time (operate_time),
    INDEX idx_operator (operator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
